version: '2'
services:
  novnc:  
    image: wcont/nv:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1200
      - DISPLAY_HEIGHT=960
    ports:
      - "80:8080"
    networks:
      - x11
networks:
  x11:
